version: '3.9'

services:
  postgres-db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mic-pet

volumes:
  pgdata: