server:
  port: 8080

spring:
  application:
    name: mic-pet
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6543/mic-pet
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver