server:
  port: 8080

spring:
  application:
    name: mic-pet
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/mic-pet
    username: postgres
    password: postgres